title: Porject/ANTH
description: Customized AI system for a efficient daylife.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
zip_url: http://github.com/emanth/anth/zipball/master
tar_url: http://github.com/emanth/anth/tarball/master
